hubot:
 build: .
 restart: always
 env_file: .env
 links:
  - db
  - elasticsearch
 ports:
  - 8080
 volumes:
  - /home/bcousin/hubot/scripts:/opt/hubot/scripts
  - /home/bcousin/hubot/bin:/opt/hubot/bin
  - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt

db:
 image: postgres
 restart: always
 env_file: .env
 volumes:
  - /app/hubot/postgres/data:/var/lib/postgresql/data
 ports:
  - "5432:5432"

elasticsearch:
 image: elasticsearch
 restart: always
 volumes:
  - "/app/hubot/elasticsearch/data:/usr/share/elasticsearch/data"
